In [1]:
import pandas as pd

In [2]:
income_percent = pd.read_csv('../data/census/income_percent.csv')

In [3]:
income_percent

,Label (Grouping),"Davidson County, Tennessee!!Households!!Estimate","Davidson County, Tennessee!!Households!!Margin of Error","Davidson County, Tennessee!!Families!!Estimate","Davidson County, Tennessee!!Families!!Margin of Error","Davidson County, Tennessee!!Married-couple families!!Estimate","Davidson County, Tennessee!!Married-couple families!!Margin of Error","Davidson County, Tennessee!!Nonfamily households!!Estimate","Davidson County, Tennessee!!Nonfamily households!!Margin of Error"
0,Total,"327,791","±3,574","164,791","±5,588","113,139","±4,798","163,000","±6,433"
1,"Less than $10,000",5.7%,±1.0,4.2%,±1.4,1.2%,±0.6,7.8%,±1.6
2,"$10,000 to $14,999",3.4%,±0.7,1.6%,±0.7,0.9%,±0.6,5.6%,±1.2
3,"$15,000 to $24,999",5.8%,±0.8,3.8%,±1.1,1.6%,±0.7,8.0%,±1.3
4,"$25,000 to $34,999",6.1%,±0.9,3.7%,±1.0,2.2%,±0.8,8.7%,±1.5
5,"$35,000 to $49,999",13.0%,±1.1,9.5%,±1.4,6.3%,±1.1,16.8%,±2.2
6,"$50,000 to $74,999",18.1%,±1.4,15.9%,±1.7,13.3%,±1.7,20.4%,±2.0
7,"$75,000 to $99,999",13.6%,±1.3,13.9%,±1.7,14.5%,±2.2,12.6%,±2.0
8,"$100,000 to $149,999",14.3%,±1.2,18.5%,±1.6,22.1%,±2.3,10.1%,±1.4
9,"$150,000 to $199,999",8.3%,±0.9,11.0%,±1.4,13.9%,±1.9,4.9%,±1.1
10,"$200,000 or more",11.8%,±1.0,17.9%,±1.7,23.9%,±2.3,5.2%,±1.0
11,Median income (dollars),"72,473","±2,059","95,250","±3,209","120,020","±5,381","52,658","±2,168"
12,Mean income (dollars),"106,423","±4,172","132,367","±5,083","160,262","±7,036","77,491","±6,438"
13,PERCENT ALLOCATED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Household income in the past 12 months,36.4%,(X),(X),(X),(X),(X),(X),(X)
15,Family income in the past 12 months,(X),(X),37.8%,(X),(X),(X),(X),(X)
16,Nonfamily income in the past 12 months,(X),(X),(X),(X),(X),(X),34.0%,(X)

In [4]:
poverty = pd.read_csv('../data/census/poverty.csv')

In [5]:
poverty

,Label (Grouping),"Davidson County, Tennessee!!Total!!Estimate","Davidson County, Tennessee!!Total!!Margin of Error","Davidson County, Tennessee!!Less than 50 percent of the poverty level!!Estimate","Davidson County, Tennessee!!Less than 50 percent of the poverty level!!Margin of Error","Davidson County, Tennessee!!Less than 100 percent of the poverty level!!Estimate","Davidson County, Tennessee!!Less than 100 percent of the poverty level!!Margin of Error","Davidson County, Tennessee!!Less than 125 percent of the poverty level!!Estimate","Davidson County, Tennessee!!Less than 125 percent of the poverty level!!Margin of Error"
0,Population for whom poverty status is determined,"687,236","±1,581",7.2%,±1.3,14.0%,±1.4,16.8%,±1.5
1,SEX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Male,"333,764","±1,935",6.1%,±1.3,11.9%,±1.6,14.4%,±1.7
3,Female,"353,472","±1,992",8.3%,±1.6,15.9%,±1.8,19.1%,±1.8
4,AGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Under 18 years,"137,918","±1,554",12.1%,±4.0,22.1%,±4.1,25.8%,±3.9
6,Related children of householder un...,"137,098","±1,649",11.6%,±4.0,21.7%,±4.1,25.4%,±3.9
7,18 to 64 years,"456,613","±1,031",6.4%,±1.0,12.2%,±1.2,14.8%,±1.2
8,65 years and over,"92,705",±909,3.9%,±1.3,10.5%,±2.0,13.3%,±2.2
9,RACE AND HISPANIC OR LATINO ORIGIN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,One race,"608,582","±7,057",6.6%,±1.2,13.0%,±1.4,15.8%,±1.5
11,White,"390,197","±2,976",4.2%,±0.8,8.6%,±1.1,10.7%,±1.2
12,Black or African American,"172,125","±4,660",12.0%,±3.7,21.3%,±4.3,24.4%,±4.4
13,American Indian and Alaska Native,"1,127",±743,0.0%,±16.9,14.1%,±22.1,14.1%,±22.1
14,Asian,"23,812","±1,904",6.0%,±5.8,16.5%,±11.8,20.7%,±10.2
15,Native Hawaiian and Other Pacific ...,408,±141,0.0%,±37.3,23.0%,±38.6,23.0%,±38.6
16,Some other race,"20,913","±3,736",8.7%,±4.7,23.9%,±10.2,33.6%,±10.4
17,Two or more races,"78,654","±7,031",12.1%,±4.8,21.6%,±6.3,25.1%,±6.5
18,Hispanic or Latino origin (of any race),"76,167",±543,14.1%,±5.3,24.3%,±6.5,29.5%,±6.1
19,"White alone, not Hispanic or Latino","383,190","±2,116",4.1%,±0.8,8.5%,±1.1,10.6%,±1.2
20,LIVING ARRANGEMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,In family households,"483,514","±9,164",6.6%,±1.8,12.3%,±2.0,14.9%,±2.1
22,In married-couple family,"331,535","±12,960",2.1%,±0.9,5.5%,±1.6,7.4%,±1.7
23,"In Female householder, no spouse p...","116,889","±9,657",19.6%,±5.9,31.2%,±5.6,35.2%,±5.7
24,In other living arrangements,"203,722","±8,833",8.7%,±1.5,18.0%,±2.1,21.4%,±2.0
25,EDUCATIONAL ATTAINMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Population 25 years and over,"493,951",±562,5.2%,±0.8,10.6%,±1.1,13.1%,±1.1
27,Less than high school graduate,"40,542","±4,699",9.8%,±3.2,24.0%,±5.1,33.0%,±5.7
28,High school graduate (includes equ...,"96,334","±7,041",9.5%,±2.4,18.9%,±3.2,22.5%,±3.3
29,Some college or associate's degree,"113,277","±6,737",5.6%,±1.4,10.5%,±2.0,13.2%,±2.3
30,Bachelor's degree or higher,"243,798","±7,475",2.5%,±0.7,5.1%,±1.0,6.1%,±1.0
31,NATIVITY AND CITIZENSHIP STATUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Native,"599,219","±9,839",7.0%,±1.3,13.4%,±1.4,16.1%,±1.4
33,Foreign born,"88,017","±9,824",8.9%,±3.2,18.4%,±5.3,21.6%,±5.3
34,Naturalized citizen,"31,223","±4,928",4.6%,±3.5,10.9%,±5.6,13.4%,±5.9
35,DISABILITY STATUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,With any disability,"88,018","±6,030",10.5%,±3.4,22.9%,±3.6,27.0%,±3.9
37,No disability,"598,678","±6,078",6.7%,±1.3,12.7%,±1.4,15.4%,±1.4
38,WORK STATUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,Population 16 to 64 years,"469,486","±1,968",6.7%,±1.0,12.6%,±1.2,15.2%,±1.3
40,"Worked full-time, year-round","281,698","±7,003",0.9%,±0.4,2.8%,±0.8,4.3%,±0.8
41,"Worked less than full-time, year-round","115,700","±7,159",11.1%,±2.3,21.0%,±2.7,25.1%,±2.7
42,Did not work,"72,088","±4,255",22.3%,±3.7,37.5%,±4.5,42.2%,±4.6

In [6]:
pc_access = pd.read_csv('../data/census/computer_access.csv')

In [7]:
pc_access

,Label (Grouping),"Davidson County, Tennessee!!Total!!Estimate","Davidson County, Tennessee!!Total!!Margin of Error","Davidson County, Tennessee!!Percent!!Estimate","Davidson County, Tennessee!!Percent!!Margin of Error"
0,Total households,"327,791","±3,574",(X),(X)
1,TYPES OF COMPUTER,NaN,NaN,NaN,NaN
2,Has one or more types of computing dev...,"317,336","±4,079",96.8%,±0.5
3,Desktop or laptop,"271,736","±5,306",82.9%,±1.3
4,Desktop or laptop with no othe...,"6,723","±1,662",2.1%,±0.5
5,Smartphone,"304,576","±4,582",92.9%,±0.8
6,Smartphone with no other type ...,"29,106","±3,448",8.9%,±1.0
7,Tablet or other portable wireless ...,"212,666","±5,753",64.9%,±1.6
8,Tablet or other portable wirel...,"3,017","±1,415",0.9%,±0.4
9,Other computer,"20,805","±3,217",6.3%,±1.0
10,Other computer with no other t...,42,±74,0.0%,±0.1
11,No computer,"10,455","±1,619",3.2%,±0.5
12,TYPE OF INTERNET SUBSCRIPTIONS,NaN,NaN,NaN,NaN
13,With an Internet subscription:,"300,871","±4,607",91.8%,±0.9
14,Dial-up with no other type of Inte...,112,±185,0.0%,±0.1
15,Broadband of any type,"300,759","±4,585",91.8%,±0.9
16,Cellular data plan,"289,782","±4,877",88.4%,±1.1
17,Cellular data plan with no...,"29,302","±3,135",8.9%,±1.0
18,"Broadband such as cable, fiber...","265,204","±5,129",80.9%,±1.2
19,Satellite Internet service,"17,035","±2,781",5.2%,±0.8
20,Without an Internet subscription,"26,920","±2,797",8.2%,±0.9
21,HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN...,NaN,NaN,NaN,NaN
22,"Less than $20,000:","36,959","±3,946",(X),(X)
23,With dial-up Internet subscription...,0,±225,0.0%,±0.6
24,With a broadband Internet subscrip...,"26,704","±3,303",72.3%,±5.0
25,Without an Internet subscription,"10,255","±2,206",27.7%,±5.0
26,"$20,000 to $74,999:","133,914","±5,446",(X),(X)
27,With dial-up Internet subscription...,112,±185,0.1%,±0.1
28,With a broadband Internet subscrip...,"120,828","±5,599",90.2%,±1.8
29,Without an Internet subscription,"12,974","±2,467",9.7%,±1.8
30,"$75,000 or more:","156,918","±4,832",(X),(X)
31,With dial-up Internet subscription...,0,±225,0.0%,±0.1
32,With a broadband Internet subscrip...,"153,227","±4,957",97.6%,±0.7
33,Without an Internet subscription,"3,691","±1,088",2.4%,±0.7